/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "channel_monitor.h"
#include "uart_driver.h"
#include "transmitter.h"

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif


int main(void) {
	init_usart2(57600,F_CPU);

	channel_monitor_init();
	transmit_init();

	printf("Enter a command (type \\h for help)\n");
	while(1) {

        printf("mcdd> ");
        char buffer[300];
        fgets(buffer, 299, stdin);
        buffer[strlen(buffer) - 1] = '\0';

        if(!strcmp(buffer, "\\h")) {
            printf("TODO: make the help text\n");
        } else if(!strcmp(buffer, "\\t")) {
        	printf("\nEnter a message: \n");
        	char message[300];
        	fgets(message, 299, stdin);
        	message[strlen(message) - 1] = '\0';
        	printf("Enter destination address: ");
        	char addr_msg[20];
        	uint8_t addr;
        	fgets(addr_msg, 19, stdin);
        	sscanf(addr_msg, "%d", (int*)&addr);
        	printf("Transmitting \"%s\" to address 0x%x\n", message, addr);
        	transmit(message, addr);
        } else if(!strcmp(buffer, "\\r")) {
        	printf("Receiving:\n");
        	recv_set();
        	recv_wait();				// takes the semaphore: interrupt owns it
        	recv_decode();				// this is the function that blocks
        } else if(!strcmp(buffer, "\\lo")) {
        	printf("Entering loopback mode: sending a message\n");
        	recv_set();
        	transmit("This is a test message", 0x15);
        	recv_wait();				// takes the semaphore: interrupt owns it
        	recv_decode();
        } else if(!strcmp(buffer, "\\bd")) {
        	printf("Entering loopback mode: sending a message\n");
        	recv_set();
          	transmit("This is a broadcast message", 0x00);
        	recv_wait();
        	recv_decode();
        } else {
            printf("Error: unknown command %s\n", buffer);
        }
	}
}
