/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "channel_monitor.h"
#include "uart_driver.h"
#include "transmitter.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void) {
	init_usart2(57600,F_CPU);

	printf("Test print\n");
	// NOTE: for some reason prints are not working, does
	// the UART get interrupted ?
	channel_monitor_init();
	transmit_init();
	printf("Enter a command (type \\h for help)\n");
    /* Loop forever */
	while(1) {
		// Example serialized data (binary)
		// Example test buffer (binary)
		uint8_t buffer1[] = {
			// Header
			0b01010101, //Preamble
			0b00010100, //Source address: 0x14
			0b00010101, //Destination address: 0x15
			0b00000001, //Length
			0b00000001, //CRC flag
			//Message (in this case, it's empty since the length is 1)
			//Trailer CRC
			0b11000000  //CRC8 FCS
		};
		size_t buffer_size = sizeof(buffer1); // Buffer size in bytes

		//Deserialize the buffer
		Packet *packet = deserializePacket(buffer1, buffer_size);

		 //Check if deserialization was successful
		if (packet != NULL) {
			printf("Deserialization successful!\n");
			printf("Source Address: 0x%02X\n", packet->header.source_address);
			printf("Destination Address: 0x%02X\n", packet->header.destination_address);
			// Free allocated memory for packet
			free(packet);
		} else {
			printf("Deserialization failed! Invalid source or destination address.\n");
		}

        printf("mcdd> ");
        char buffer[300];
        fgets(buffer, 299, stdin);
        buffer[strlen(buffer) - 1] = '\0';

        if(!strcmp(buffer, "\\h")) {
            printf("TODO: make the help text\n");
        } else if(!strcmp(buffer, "\\t")) {
        	printf("\nEnter a message: \n");
        	char message[300];
        	fgets(message, 299, stdin);
        	get_transmission(message);
        } else if(!strcmp(buffer,"\null")) {
            get_transmission("\\0");
        } else if(!strcmp(buffer, "\\r")) {
        	printf("Receiving:\n");
        	recv_set();
        	recv_wait();				// takes the semaphore: interrupt owns it
        	recv_decode();				// this is the function that blocks
        } else {
            printf("Error: unknown command %s\n", buffer);
        }


	}
}
